### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by danielarnason** [regiongis/statistikbanken#1]
Hvis det skal blive et plugin i qgis, så er det nok smartest, at vi skriver det i Python 2.7.

**Comment by baffioso** [comment]
Enig, så må vi skrive det om når QGIS 3 kommer, hvis det der kommer noget godt ud af det

**Comment by danielarnason** [comment]
Der står på hjemmesiden, at de anbefaler, at man bruger POST i stedet for GET, når man henter data. Der er  et modul, der hedder _requests_, som er ret nemt at bruge til det. Jeg har tilføjet det, og skrevet det om til Python2.7. 

Kig i python2 branch

**Comment by danielarnason** [comment]
Der gik totalt ged i mine commits, men det burde virke :)
