### ISSUE TITLE
Arbejdsgang

### ISSUE THREAD

**Issue by danielarnason** [regiongis/statistikbanken#13]
Jeg har læst lidt op på, hvordan man smart arbejder sammen på Github :)

Jeg synes, at vi skal arbejde på rettelser i vores egne branches, og kun committe til den, og så pushe det til GitHub. Så kan man lave en pull request her inde. På den måde kan vi holde hinanden opdateret med, hvad vi har lavet :)

Det her er en god artikel om det.
https://www.atlassian.com/git/tutorials/making-a-pull-request

**Comment by baffioso** [comment]
Enig. Den kører vi med fra nu af
