### ISSUE TITLE
Mangler plus ikon for hovedemner i treewidget

### ISSUE THREAD

**Issue by baffioso** [regiongis/statistikbanken#22]
På min linux maskine har jeg ikke plus-ikon/pil som indikerer at træet kan foldes ud når jeg åbner pluginnet -
det komme først frem når jeg har trykket på et emne.
image
![image](https://user-images.githubusercontent.com/7534153/29890538-42b76c8c-8dc8-11e7-8e06-7f37db88ba91.png)

@danielarnason Er de der fra start på din mac?

**Comment by danielarnason** [comment]
@baffioso Nej, det er det samme hos mig. Det skal jeg nok kigge på på et tidspunkt.

**Comment by danielarnason** [comment]
@baffioso Jeg får pile frem med det samme. "Problemet" var, at der ikke var nogen data i kategorierne før man klikkede på dem. Nu henter plugin'et data første gang det bliver kørt.
