### ISSUE TITLE
Færdiggør get_data()

### ISSUE THREAD

**Issue by HenningJagd** [regiongis/statistikbanken#4]

**Comment by baffioso** [comment]
Ikke så kønt endnu, men kan nu hente data med følgende:
```
kommuner = ["151", "169"]
tid = ["2017K1", "2016K3"]

post_body = \
    {
       "table": "folk1a",
       "format": "JSONSTAT",
       "variables": [
          {
             "code": "OMRÅDE",
             "values": kommuner

          },
          {
             "code": "TID",
             "values": tid
          }
       ]
    }

def get_data(post_body):
    endpoint = 'data'
    return get_json('http://api.statbank.dk/v1/', endpoint, post_body)
```
@HenningJagd  @danielarnason Vil lige have input til variablen `post_body` som blot er kopieret fra [API konsollen](http://api.statbank.dk/console#data). Skal der laves særskilt funktion som tager brugernes valg og genererer post_body som så kan bruges som parameter i `get_data()` eller skal det inkluderes direkte i `get_data() `?

**Comment by danielarnason** [comment]
På sigt skal vi nok lave sådan en funktion, men lad os bare starte med at få de grundlæggende funktioner til at fungere. Den er måske lidt nemmere at lave/teste, når vi har et udkast til en gui.
