### ISSUE TITLE
Skabelon til et plugin

### ISSUE THREAD

**Issue by danielarnason** [regiongis/statistikbanken#7]
Jeg bruger plugin builder'en i qgis til at danne de nødvendige filer

**Comment by danielarnason** [comment]
Har tilføjet en folder, som indeholder et skabelon for et qgis plugin. Der er ingen funktionalitet i den endnu, men den kommer på et tidspunkt :)

**Comment by danielarnason** [comment]
@baffioso Jeg har åbnet det her igen. Jeg har flyttet lidt på filerne, så det er nemt at teste en gui i QGIS. Hvis du bare cloner hele det her repo ned i plugin folderen for qgis, så kan du finde plugin'et i plugin manager.
Du skal bare huske at skifte til 'class' branchen, før du starter qgis :)

Der er ingen funktionalitet endnu i plugin'et, men nu kan vi teste treeview'et og alt det andet.

**Comment by baffioso** [comment]
@danielarnason hvorfor genåbnet?
