### ISSUE TITLE
Se på jsonstat.py

### ISSUE THREAD

**Issue by baffioso** [regiongis/statistikbanken#8]
Kan være vi skal se på dette modul til at håndtere data fra DST. http://jsonstatpy.readthedocs.io/en/latest/

**Comment by danielarnason** [comment]
Skulle vi ikke holde os til standard moduler fra Python, så det ikke ville give bøvl, når vi laver det til et pllugin?

**Comment by baffioso** [comment]
Jo. Kiggede lige på https://json-stat.org/ som har et slideshow der beskriver hvordan jsonstat er opbygget. Tror der skal skrives en funktion som sørger for at få det om i et format som vi kan joine med geojson i QGIS. Alternativt kan vi hente data som CSV fra statistikbanken

**Comment by baffioso** [comment]
Vi henter csv
